# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/AbcSize:
  Max: 19

Metrics/ClassLength:
  Max: 172

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 14

Metrics/ModuleLength:
  Max: 156

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
